### ISSUE TITLE
does not work with Qtdark.Stylesheet

### ISSUE THREAD

**Issue by NektoNektovich** [pkgforge-dev/strawberry-AppImage#2]
Everything is good, but it does not work with Qtdark.Stylesheet, although QBittorrent.appimage works :(

[QTDark.zip](https://github.com/user-attachments/files/17924012/QTDark.zip)

**Comment by Samueru-sama** [comment]
What is Qtdark.Stylesheet? Is that how you set themes with kde? 

The AppImage has theme support with qt6ct, so if you have it installed and `export QT_QPA_PLATFORMTHEME=qt6ct` you can get a working dark theme: 

![image](https://github.com/user-attachments/assets/e5c5e380-e016-4db8-a32d-91cab44d3236)

>although QBittorrent.appimage works :(

Really? the qbittorrent appimage was notorious for having a broken theme, and as far as I know the issue about this is still open. 

The `qbittorrent-enhanced` fork which also has an appimage did have a working theme support, but it broke recently and was fixed but I think they still haven't made a new release that includes the fix though.


In any case, I want to fix this issue but I need to know how you are setting the theme?

**Comment by NektoNektovich** [comment]
> Что такое Qtdark.Таблица стилей? Так вы настраиваете темы в kde?
> 
> AppImage поддерживает темы с qt6ct, поэтому, если у вас они установлены и `export QT_QPA_PLATFORMTHEME=qt6ct` вы можете получить рабочую темную тему:
> 
> ![image](https://private-user-images.githubusercontent.com/36420837/390092605-e5c5e380-e016-4db8-a32d-91cab44d3236.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MDY2MDksIm5iZiI6MTczMjcwNjMwOSwicGF0aCI6Ii8zNjQyMDgzNy8zOTAwOTI2MDUtZTVjNWUzODAtZTAxNi00ZGI4LWEzMmQtOTFjYWI0NGQzMjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDExMTgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZmU5NGE2ZTg2M2MzMWQwZWVmMWJjMzUwYTVlZWMzMGRlY2VkNTliYWY0Mzc1NjY3MTJlNGUzM2U4YmZiNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Zg0huUrwOgLiKptPNStoBpdlP52fhoIIMr8qWxwDaeM)
> 
> > хотя qBittorrent.appimage работает :(
> 
> Правда? приложение qbittorrent appimage было печально известно тем, что имело неработающую тему, и, насколько я знаю, вопрос об этом все еще открыт.
> 
> В `qbittorrent-enhanced` у fork, у которого также есть appimage, действительно была поддержка рабочей темы, но недавно она сломалась и была исправлена, но я думаю, что они все еще не выпустили новый релиз, который включал бы исправление.
> 
> В любом случае, я хочу исправить эту проблему, но мне нужно знать, как вы настраиваете тему?

I have LXQT 2.1.0. For the official QBittorrent-5.0.1.Appimage, I made the launch button in the menu:
 /Home/User/Path for/QBittorrent -stylesheet/Home/User/Path For/Qtdark.stylesheet and it starts dark. I did the same for your Strawberry.Appimage, but it does not start at all, although if you remove the path to Qtdark.Stylesheet, then the player starts.

**Comment by Samueru-sama** [comment]
I didn't know you could do this with Qt apps. I tested it with qbittorrent-enhanced and indeed it changes the theme. 

![image](https://github.com/user-attachments/assets/c3c18cf4-ed98-4a75-a010-0139083ab0b0)

--------------------------------------------------------------------------------

However it does not work with strawberry, **and this also happens with the native strawberry package**: 

![image](https://github.com/user-attachments/assets/b6e7d173-a463-48d1-86e6-777c2801ba7e)

strawberry doesn't like when I pass `-stylesheet ./QTDark.stylesheet` so I tried `-- -stylesheet ./QTDark.stylesheet` and that causes it to hang without opening and then segfaulted as I was writting this lol:

![image](https://github.com/user-attachments/assets/9aa5213b-d004-4f3a-8bd3-9c846f61d9c4)


Given that this happens with the native strawberry package there isn't anything I can do, this is not an issue specific to the AppImage, I can only suggest that you use [`qt6ct`](https://github.com/trialuser02/qt6ct) to set dark theme.

**Comment by NektoNektovich** [comment]
Sadly, but many thanks for that!

**Comment by Samueru-sama** [comment]
> Sadly, but many thanks for that!

Btw thanks for letting me know about this flag, I can't even find documentation about `-stylesheet`, how did you find this?

**Comment by NektoNektovich** [comment]
> > Sadly, but many thanks for that!
> 
> Btw thanks for letting me know about this flag, I can't even find documentation about `-stylesheet`, how did you find this?

a kid3 developer helped me when I asked for help with a static build of kid3  https://bugs.kde.org/show_bug.cgi?id=493915

**Comment by Samueru-sama** [comment]
> > > Sadly, but many thanks for that!
> > 
> > 
> > Btw thanks for letting me know about this flag, I can't even find documentation about `-stylesheet`, how did you find this?
> 
> a kid3 developer helped me when I asked for help with a static build of kid3 https://bugs.kde.org/show_bug.cgi?id=493915

Interesting, well I just added support to this method to [all my Qt appimages where it works](https://github.com/pkgforge-dev/puddletag-AppImage/blob/main/puddletag-appimage.sh#L56-L57).

Basically if you create a stylesheet file next to the AppImage with the name of the AppImage + `.stylesheet`, which in this example it would be ` puddletag-2.4.0-anylinux-x86_64.AppImage.stylesheet` the appimage will automatically use that as its theme. No need to be editing files.

You can also place one stylesheet file in say `~/.local/share/Qt-dark.stylesheet` and in your `.bashrc` add `export APPIMAGE_QT_THEME="$HOME/.local/share/Qt-dark.stylesheet"` and now all appimages that have this will automatically use that stylesheet.

**Comment by NektoNektovich** [comment]
> > > > К сожалению, но большое спасибо за это!
> > > 
> > > 
> > > Кстати, спасибо, что сообщили мне об этом флаге, я даже не могу найти документацию по  `-stylesheet`- как ты это нашел?
> > 
> > 
> > разработчик kid3 помог мне, когда я попросил помощи со статической сборкой kid3  [https://bugs.kde.org/show_bug.cgi?id=493915 ](https://bugs.kde.org/show_bug.cgi?id=493915)
> 
> Интересно, что я только что добавил поддержку этого метода во [все мои изображения приложений Qt, где он работает ](https://github.com/pkgforge-dev/puddletag-AppImage/blob/main/puddletag-appimage.sh#L56-L57).
> 
> В принципе, если вы создадите файл таблицы стилей рядом с AppImage с именем AppImage + `.stylesheet`, который в данном примере был бы ` puddletag-2.4.0-anylinux-x86_64.AppImage.stylesheet` изображение приложения автоматически будет использовать это в качестве своей темы. Нет необходимости редактировать файлы.
> 
> Вы также можете поместить один файл таблицы стилей, скажем, в `~/.local/share/Qt-dark.stylesheet` и в вашем `.bashrc` Добавить `export APPIMAGE_QT_THEME="$HOME/.local/share/Qt-dark.stylesheet"` и теперь все изображения приложений, у которых есть это, будут автоматически использовать эту таблицу стилей.

Thank you, it's interesting, I will know!
